### PR TITLE
Added additional attributes

### PR DESCRIPTION
**Pull request by FeikoJoosten**
I've added support for the current market state and the pre/post/regular market times. This allows you to actually make use of the postMarketValues, as you can now use it in your templates to retrieve the after/post market values.

Example for updating config for showing the current market value base on the post market state:
Note: This example makes use of [template-entity-row](https://github.com/thomasloven/lovelace-template-entity-row)

```
definitions: &finance_template
    type: 'custom:template-entity-row'
    secondary: 'Marketstate: {{state_attr(config.entity, "marketState")}}'
    state: >
      {% if state_attr(config.entity, "postMarketTime")==0 %}
        {% set time=state_attr(config.entity, "preMarketTime") %}
      {% else %}
        {% set time=state_attr(config.entity, "postMarketTime") %}
      {% endif %}  {% if time > state_attr(config.entity, "regularMarketTime")
      %} 
        {% if state_attr(config.entity, "postMarketPrice")==0 %}
          {{state_attr(config.entity, "preMarketPrice")}}   
        {% else %} {{state_attr(config.entity, "postMarketPrice")}}   
        {% endif %}
      {% else %} {{states(config.entity)}}  {% endif %}
    style: >
      :host {
        --paper-item-icon-color: 
          {% if state_attr(config.entity, "postMarketTime")=="0" %}
            {% set time=state_attr(config.entity, "preMarketTime") %}
          {% else %}
            {% set time=state_attr(config.entity, "postMarketTime") %}
          {% endif %}
          {% if time > state_attr(config.entity, "regularMarketTime") %}
            {% if state_attr(config.entity, "postMarketChange")==0 %}
              {% set value=state_attr(config.entity, "preMarketChange") %}
            {% else %}
              {% set value=state_attr(config.entity, "postMarketChange") %}
            {% endif %}
          {% else %} 
            {% set value=state_attr(config.entity, "regularMarketChange") %}
          {% endif %}
          {% if value > 0 %} green
          {% elif value < 0 %} red
          {% else %} var(--paper-item-icon-color))
          {% endif %};
type: entities
title: Finances
entities:
  - entity: yahoofinance.gme
    <<: *finance_template
  - entity: yahoofinance.rblx
    <<: *finance_template
```

The configuration above results in: 
image

I'm also proposing a change where an attribute is added that does the post/pre market checks through python. But I (or someone else) still has to write code for that.

### CODE REVIEW

**Comment by backslashV** [comment]
Hi,
Where can I read about the & and <<: usage for Home Assistant?

Thanks

**Comment by FeikoJoosten** [comment]
That's what's called yaml achors. https://support.atlassian.com/bitbucket-cloud/docs/yaml-anchors/

**Comment by backslashV** [comment]
Thanks a lot.

**Comment by iprak** [comment]
@FeikoJoosten Due to increasing number of attributes, do you think that these new attributes can be optionally included via a setting? I know I already merged the changes but I can introduce a setting over the weekend.

**Comment by FeikoJoosten** [comment]
Hmm the only thing I can think of is to create something inside of the configuration.yaml which lets you define additional string and numerical attributes. Something like:

```
yahoofinance:
  string_attributes:
   - marketState
  numerical_attributes:
   - preMarketTime
  currency_attributes:
   - preMarketChange
```

Where the currency attributes allow you to process the currency conversion.

**Comment by iprak** [comment]
How about just a single setting like  'include_market_states: true" since it is most likely that all of them settled beer used together?

**Comment by FeikoJoosten** [comment]
That could work as well, but my suggestion future proves it in case people want even more attributes.

**Comment by iprak** [comment]
I see your point but individually defining each attribute seems too cumbersome.

I looked at the attributes again and think the settings should be something like `include_pre_attributes`, `include_post_attributes`, `inclued_two_hundred_day_attributes`, `inclued_fifty_day_attributes`. And the regular market attributes should be part of the basic set and would not be optional.

But this would be a breaking change.

My concern was regarding database size if values are being tracked for weeks/months ([Recorde](https://www.home-assistant.io/integrations/recorder/)r's default purge_keep_days is 10 days). Thoughts?

**Comment by FeikoJoosten** [comment]
Hmm, I'm pretty sure only the actual entity state is being tracked in the history database (although I could be wrong, no expert HA developer or something). So I don't think that would matter at all.

**Comment by FeikoJoosten** [comment]
Yeah, from what I can see at the recorder documentation, it only records events and states. So any additional attribute shouldn't matter at all.

**Comment by iprak** [comment]
My concern was based on what I read for the [history](https://www.home-assistant.io/integrations/history/) component which uses recorder and says that "JSON of the state attributes" is saved. 

I opened up my db in DB Browser for SQLite and saw attributes in the table definition:
image

I saw all the attributes saved and yahoo entities have the largest size of attributes (for me). So I think restricting attributes would be useful .. less read/write.

This also made me realize that a lot of unnecessary stuff is getting saved and I should look at my configuration.

**Comment by FeikoJoosten** [comment]
Hmm, I feel like the docs require some additional information then. Especially because the logbook and history viewer in HA don't list the attributes at all.

**Comment by iprak** [comment]
I have created a separate issue (#39) for this. This will be optional and can be used to turn off attributes which one might not care about from being saved.

**Pull request merged**
