### PR TITLE
Handle cookies consent page

### LINKED ISSUE #96: All Sensors stopped working
HA 2023.4.6 and HA 2023.5.1

All Sensors stopped working since yesterday:
Error Log:

2023-05-05 08:32:53.184 ERROR (MainThread) [custom_components.yahoofinance.coordinator] Received status 401 (error=Unauthorized) for https://query1.finance.yahoo.com/v7/finance/quote?symbols=EBK.DE,O2D.DE,LHA.DE,CL=F,EURUSD=X,ERDZ.MU,JPJX.MU,HSIC,0P000151AI.F,LU1019989323.SG,ZZR8.F,FLRG.DE,NRJ.PA,DBK.DE

### PR DESCRIPTION
**Pull request by swiergot**
Fixes #96.

### CODE REVIEW

**Comment by iprak** [comment]
I am seeing https://consent.yahoo.com/ being accessible, maybe it is region specific.
image

I have been playing with a different approach of first navigating to yahoo.com and grabbing the cookies from there. And then navigating to `https://query1.finance.yahoo.com/v1/test/getcrumb`. The latter appears when accessing `https://finance.yahoo.com/quote/NQ%3DF`.

**Comment by swiergot** [comment]
When I simply go to consent.yahoo.com, I get the error page too. But when I open an incognito window and go to https://finance.yahoo.com/quote/NQ%3DF, I get redirected to consent.yahoo.com with some parameters. I think it just requires a valid session or something which is created only on regular pages.

It is the same every time I start with a fresh incognito window. The same happens to my HA when your component tries to open https://finance.yahoo.com/quote/NQ%3DF for the first time. After the consent form is submitted (with my changes), it redirects to https://finance.yahoo.com/quote/NQ%3DF and everything is as it used to be.

If you don't live in the EU, it is entirely possible that you will never be shown the cookies consent screen as it is required by the EU law. I suppose some websites take the easy way and show the consent form to everyone without exception, but there are also websites that show it or not based on geolocation.

**Comment by iprak** [comment]
That makes sense, I have never seen that consent page. I did VPN to Germany but still was not able to access that consent page.
In US, the request just errors out with 401. What do you get if you were to browse to yahoo.com in incognito ?

**Comment by swiergot** [comment]
I assume you tried incognito when on VPN?

**Comment by swiergot** [comment]
Just to be clear, API URLs do not redirect to consent.yahoo.com, only yahoo.com and finance.yahoo.com do.

I have also tried https://query1.finance.yahoo.com/v1/test/getcrumb but it works only after I visit yahoo.com and submit the consent form. So no real gain.

**Comment by swiergot** [comment]
One additional note - this PR also fixes a bug in handling of crumbs containing a slash character encoded as a Unicode escape sequence.

Not related to the consent page. I suspect it is the reason why sometimes sensors become unavailable and come back after a while.

**Comment by iprak** [comment]
Got it. It works well from US region. Could we add something to the logging to differentiate it from the same logging within CONSENT_HOST check?

```
   _LOGGER.debug("Response status: %d", response.status)
   _LOGGER.debug("Response URL: %s", response.url)
```

**Pull request merged**
